### ISSUE TITLE
Support for arrays

### ISSUE THREAD

**Issue by jtietema** [LachlanMcKee/gsonpath#50]
It would be great if we could select a specific item in an array. (Say you always get an item wrapped in an array, being able to extract from that (useless) wrapper array).

``` java
@SerializedName("items[0].episodeNumber")
int episodeNumber;
```

Let me know what you think.

**Comment by LachlanMcKee** [comment]
Hi @jtietema

Thanks for the suggestion, that sounds like a cool idea! 

I can see that would work in the normal scenario, but what would you expect to occur when the array is null or empty? 

I suppose it could use the field validation (or maybe a new validation type) to let the developer decide whether it should use the default value or throw an exception. 

Thoughts?

**Comment by jtietema** [comment]
Throwing an exception would make most sense in my opinion, as I would
only use this if I am absolutely sure about the amount of items
returned, otherwise I would just use a list of items.

On Tue, Sep 13, 2016, at 12:32 PM, Lachlan McKee wrote:
> Hi @jtietema[1]
> Thanks for the suggestion, that sounds like a cool idea!
> I can see that would work in the normal scenario, but what would you
> expect to occur when the array is null or empty?
> I suppose it could use the field validation (or maybe a new validation
> type) to let the developer decide whether it should use the default
> value or throw an exception.
> Thoughts?
> — You are receiving this because you were mentioned. Reply to this
> email directly, view it on GitHub[2], or mute the thread[3].
>


Links:

  1. https://github.com/jtietema
  2. https://github.com/LachlanMcKee/gsonpath/issues/50#issuecomment-246555719

**Comment by LachlanMcKee** [comment]
Finally releasing this feature in version 3.0.0 :)
