### ISSUE TITLE
Generate multiple GeneratedTypeAdapterLoaders to enable package private models

### ISSUE THREAD

**Issue by LachlanMcKee** [LachlanMcKee/gsonpath#58]
At the moment due to the way in which the TypeAdapterFactory works, every POJO must be public.

The intended change is that a `GeneratedTypeAdapterLoader` will be created in all packages that classes annotated with `@AutoGsonAdapter` exist. This will mean that the POJOs can be be package private if required.

**Comment by lnanek** [comment]
Nice, I've actually had to add checkstyle exceptions due to this, but once done I could make my fields package private again and remove the exception for annotated classes.

**Comment by LachlanMcKee** [comment]
Hi @lnanek 

This feature has now been released in version 1.7.0!
It should be available in maven in the next hour or so.
